### ISSUE TITLE
re-image kc-strip for agoric incentivized testnet

### ISSUE THREAD

**Issue by dckc** [dckc/madmode-blog#115]
In preparation for the Agoric incentivized testnet, I plan to re-image kc-strip.madmode.com . @jimscarver the transaction indexing service we used to prototype [vote tallying](https://github.com/rchain-community/rv2020/blob/9c01d5936d1bba84453084e6f58c9eb512905672/src/cli/tally.sh#L10) runs there    . Do you want it to continue to be available? If so, care to recommend alternative hosting? Or at least a place to backup the database during the re-image? @zsluedem do we have some other testnet transaction indexing service?

**Comment by zsluedem** [comment]
Today I updated https://github.com/zsluedem/transaction-server to abstract the database layer. I am thinking to implement other stroage like mongo. Do you have particular preference?

Besides, I want to transfer transaction_server to rchain-community so that you guys might feel better on maintain it together.

**Comment by dckc** [comment]
All I plan to do is allow others to take advantage of the investment I / we have made in indexing the testnet so far... i.e. save someone else the trouble of starting from genesis. I don't see how a different database helps with that.

**Comment by zsluedem** [comment]
> take advantage of the investment

what do you mean about that?

My ultimate goal is that we don't need transaction server and rnode should include this ability.

**Comment by dckc** [comment]
> > take advantage of the investment
> 
> what do you mean about that?

I mean the fact that my machine has been indexing testnet transactions for months. Starting over would take a long, long time to catch up.

> My ultimate goal is that we don't need transaction server and rnode should include this ability.

Do you have a schedule for that? My estimation is that it is >= 6 months away.

I don't mind just shutting down my service, but @jimscarver wanted to keep such a service available.

**Comment by zsluedem** [comment]
> I mean the fact that my machine has been indexing testnet transactions for months. Starting over would take a long, long time to catch up.

Wow, that's great. To answer your original question, I believe I got no full testnet transaction data and I don't think coop got one either.

> Do you have a schedule for that? My estimation is that it is >= 6 months away.
Sorry. I don't have a schedule for that.

**Comment by dckc** [comment]
I just backed up the code and DB and stopped the service:

 - [rchain-tx-server.tar.gz](https://drive.google.com/file/d/10qlbZtAB8EUCW7JU1Jym1R6Gv9jeu3CJ/view?usp=sharing)

**Comment by dckc** [comment]
Overtaken be events.
