### ISSUE TITLE
Archives column should be in order

### ISSUE THREAD

**Issue by ocdtrekkie** [dckc/madmode-blog#91]
I momentarily wondered if your site had not been posted to since 2015. However, I see that it goes 2015 -> 2001, and then, confusingly, goes from 2020 -> 2016. This puts the current year in the middle of the listed years... if you guessed the most recent year of the archives was either at the top or the bottom of the list, you'd be wrong. But 2020 is there, just somewhere in the middle nearish to the bottom.

I tried to figure out where you had this coded, and it looks like you're maybe building it dynamically from the years you have posts in. Perhaps such statements just need a good 'sort by' added to them?

![image](https://user-images.githubusercontent.com/4399499/87565497-54929a80-c687-11ea-8950-d1b9cda8abe4.png)

**Comment by dckc** [comment]
fixed in 4fb1925

thanks for the nudge
